'use client';
import Link from 'next/link';
import { Check, Download, Printer } from 'lucide-react';
import { PortalFooter } from '@/components/portal-footer';
import { PortalNav } from '@/components/portal-nav';
import { useParams } from 'next/navigation';
import { useEffect, useState } from 'react';
import { apiJson } from '@/lib/api';
export default function ConfirmationPage() { const params = useParams<{ bookingRef: string }>(); const [booking, setBooking] = useState<{ bookingRef: string; totalPaise: number } | null>(null); const [error, setError] = useState(''); useEffect(() => { if (params.bookingRef) void apiJson<{ bookingRef: string; totalPaise: number }>(`/bookings/${params.bookingRef}`).then(setBooking).catch(() => setError('This booking could not be found for your account.')); }, [params.bookingRef]); return <main className="confirmation-page"><PortalNav /><section className="confirmation-wrap"><div className="confirmation-mark"><Check size={26}/></div><span className="eyebrow">{error ? 'Booking unavailable' : booking ? 'Booking confirmed' : 'Loading booking'}</span><h1>{error ? <>We couldn’t<br/><em>find it.</em></> : <>Your ticket<br/><em>is waiting.</em></>}</h1><p className="confirmation-sub">{error || (booking ? 'Your booking is saved against your account.' : 'Retrieving your confirmed booking…')}</p>{booking && <article className="ticket-stub"><div><span className="ticket-status">Confirmed booking</span><h2>Encore ticket</h2><p>Booking reference {booking.bookingRef}</p><div className="stub-meta"><span><small>Reference</small>{booking.bookingRef}</span><span><small>Total</small>₹{Math.round(booking.totalPaise / 100).toLocaleString('en-IN')}</span></div></div><div className="ticket-qr"><div className="qr-grid"/><small>REF // {booking.bookingRef}</small></div></article>}<div className="confirmation-actions"><Link href="/bookings" className="coral-button"><Download size={16}/> My tickets</Link><button className="ghost-button" onClick={() => window.print()}><Printer size={16}/> Print receipt</button></div></section><PortalFooter /></main>; }
