import 'dotenv/config';
import { NestFactory } from '@nestjs/core';
import { Body, Controller, Delete, Get, HttpException, Injectable, Module, Param, Patch, Post, Query, Req, Res, UnauthorizedException, BadRequestException, ConflictException, NotFoundException } from '@nestjs/common';
import { APP_GUARD, Reflector } from '@nestjs/core';
import { CanActivate, ExecutionContext, SetMetadata } from '@nestjs/common';
import { ThrottlerGuard, ThrottlerModule } from '@nestjs/throttler';
import * as argon2 from 'argon2';
import * as jwt from 'jsonwebtoken';
import { createHash, randomBytes, randomUUID } from 'node:crypto';
import type { Request, Response } from 'express';
import { and, asc, desc, eq, gt, inArray, isNull, sql } from 'drizzle-orm';
import { confirmSchema, eventCreateSchema, holdSchema, loginSchema, passwordResetRequestSchema, passwordResetSchema, registerSchema, roleSchema, seatAvailabilitySchema, showCreateSchema, waitlistSchema, type Role } from '@encore/shared';
import { db } from './db/client';
import { bookingSeats, bookings, events, holds, jobs, passwordResetTokens, payments, refreshTokens, seats, showSeats, shows, users, venues, waitlistEntries } from './db/schema';
import { startWorker } from './worker';
import { RealtimeGateway } from './realtime.gateway';

type AccessPayload={sub:string;name:string;email:string;role:Role};
declare global { namespace Express { interface Request { user?: AccessPayload } } }
export const IS_PUBLIC_KEY='isPublic'; export const Public=()=>SetMetadata(IS_PUBLIC_KEY,true);
const ROLES_KEY='roles'; export const Roles=(...roles:Role[])=>SetMetadata(ROLES_KEY,roles);
const secret=()=>process.env.JWT_ACCESS_SECRET||'local-development-secret';
const digest=(value:string)=>createHash('sha256').update(value).digest('hex');
const accessToken=(u:{id:string;name:string;email:string;role:Role})=>jwt.sign({sub:u.id,name:u.name,email:u.email,role:u.role},secret(),{expiresIn:'15m'});
function setCookie(res:Response,name:string,value:string,maxAge:number){res.cookie(name,value,{httpOnly:true,secure:process.env.NODE_ENV==='production',sameSite:'lax',maxAge,path:'/'})}
function auth(req:Request){if(!req.user)throw new UnauthorizedException();return req.user}

@Injectable() class AuthGuard implements CanActivate{constructor(private reflector:Reflector=new Reflector()){}canActivate(ctx:ExecutionContext){if(this.reflector.getAllAndOverride<boolean>(IS_PUBLIC_KEY,[ctx.getHandler(),ctx.getClass()]))return true;const req=ctx.switchToHttp().getRequest<Request>();const raw=req.cookies?.encore_access;if(!raw)throw new UnauthorizedException();try{req.user=jwt.verify(raw,secret()) as AccessPayload;const allowed=this.reflector.getAllAndOverride<Role[]>(ROLES_KEY,[ctx.getHandler(),ctx.getClass()]);if(allowed&&!allowed.includes(req.user.role))throw new UnauthorizedException();return true}catch(error){if(error instanceof UnauthorizedException)throw error;throw new UnauthorizedException()}}}

@Controller()
class RootController {
  @Public() @Get('') root() {
    return { status: 'ok', service: 'encore-api', health: '/api/health' };
  }
  @Public() @Get('health') async health() {
    try {
      await db.execute(sql`select 1`);
      return { status: 'ok', service: 'encore-api', database: true };
    } catch {
      return { status: 'degraded', service: 'encore-api', database: false };
    }
  }
}

@Controller('api')
class AppController{
 constructor(private readonly realtime:RealtimeGateway){}

 // ── Health ──────────────────────────────────────────────────────────────────
 @Public() @Get('health') async health(){try{await db.execute(sql`select 1`);return {status:'ok',service:'encore-api',database:true}}catch{return {status:'degraded',service:'encore-api',database:false}}}

 // ── Events (public) ─────────────────────────────────────────────────────────
 @Public() @Get('events') async listEvents(){const rows=await db.select({id:events.id,title:events.title,description:events.description,type:events.type,posterUrl:events.posterUrl,showId:shows.id,startsAt:shows.startsAt,venue:venues.name,city:venues.city}).from(events).innerJoin(shows,eq(shows.eventId,events.id)).innerJoin(venues,eq(venues.id,shows.venueId));return {events:rows}}

 // ── Organiser: create event ──────────────────────────────────────────────────
 @Roles('organiser','admin') @Post('organiser/events') async createEvent(@Body() body:unknown,@Req() req:Request){const u=auth(req);const input=eventCreateSchema.safeParse(body);if(!input.success)throw new BadRequestException('Invalid event details');return (await db.insert(events).values({...input.data,organiserId:u.sub}).returning({id:events.id,title:events.title}))[0]}

 // ── Organiser: list own events ───────────────────────────────────────────────
 @Roles('organiser','admin') @Get('organiser/events') async listOwnEvents(@Req() req:Request){const u=auth(req);const filter=u.role==='admin'?undefined:eq(events.organiserId,u.sub);const rows=await db.select({id:events.id,title:events.title,type:events.type,posterUrl:events.posterUrl,createdAt:events.createdAt}).from(events).where(filter).orderBy(desc(events.createdAt));return {events:rows}}

 // ── Organiser: event detail ──────────────────────────────────────────────────
 @Roles('organiser','admin') @Get('organiser/events/:eventId') async getOwnEvent(@Param('eventId') eventId:string,@Req() req:Request){const u=auth(req);const row=(await db.select().from(events).where(u.role==='admin'?eq(events.id,eventId):and(eq(events.id,eventId),eq(events.organiserId,u.sub))).limit(1))[0];if(!row)throw new NotFoundException('Event not found');return row}

 // ── Organiser: create show ───────────────────────────────────────────────────
 @Roles('organiser','admin') @Post('organiser/shows') async createShow(@Body() body:unknown,@Req() req:Request){const u=auth(req);const input=showCreateSchema.safeParse(body);if(!input.success)throw new BadRequestException('Invalid show details');const owned=(await db.select({id:events.id}).from(events).where(and(eq(events.id,input.data.eventId),eq(events.organiserId,u.sub))).limit(1))[0];if(!owned&&u.role!=='admin')throw new UnauthorizedException();return (await db.insert(shows).values(input.data).returning({id:shows.id,eventId:shows.eventId,venueId:shows.venueId,startsAt:shows.startsAt}))[0]}

 // ── Organiser: list shows for event ─────────────────────────────────────────
 @Roles('organiser','admin') @Get('organiser/events/:eventId/shows') async listShows(@Param('eventId') eventId:string,@Req() req:Request){const u=auth(req);const owned=(await db.select({id:events.id}).from(events).where(u.role==='admin'?eq(events.id,eventId):and(eq(events.id,eventId),eq(events.organiserId,u.sub))).limit(1))[0];if(!owned)throw new NotFoundException('Event not found');const rows=await db.select({id:shows.id,startsAt:shows.startsAt,venue:venues.name,city:venues.city}).from(shows).innerJoin(venues,eq(venues.id,shows.venueId)).where(eq(shows.eventId,eventId)).orderBy(asc(shows.startsAt));return {shows:rows}}

 // ── Organiser: update seat availability ──────────────────────────────────────
 @Roles('organiser','admin') @Patch('organiser/shows/:showId/seats/:showSeatId') async updateSeatAvailability(@Param('showId') showId:string,@Param('showSeatId') showSeatId:string,@Body() body:unknown,@Req() req:Request){const u=auth(req);const input=seatAvailabilitySchema.safeParse(body);if(!input.success)throw new BadRequestException('Invalid seat status');const owner=(await db.select({organiserId:events.organiserId}).from(showSeats).innerJoin(shows,eq(shows.id,showSeats.showId)).innerJoin(events,eq(events.id,shows.eventId)).where(and(eq(showSeats.id,showSeatId),eq(showSeats.showId,showId))).limit(1))[0];if(!owner||(u.role!=='admin'&&owner.organiserId!==u.sub))throw new UnauthorizedException();const updated=(await db.update(showSeats).set({status:input.data.status,heldByUserId:null,heldUntil:null,heldPricePaise:null,version:sql`${showSeats.version}+1`}).where(and(eq(showSeats.id,showSeatId),eq(showSeats.showId,showId),sql`${showSeats.status} <> 'booked'`)).returning({id:showSeats.id,status:showSeats.status}))[0];if(!updated)throw new ConflictException('Booked seats cannot be changed');this.realtime.emitSeatUpdate(showId);return updated}

 // ── Organiser: show bookings ─────────────────────────────────────────────────
 @Roles('organiser','admin') @Get('organiser/shows/:showId/bookings') async showBookings(@Param('showId') showId:string,@Req() req:Request){const u=auth(req);const show=(await db.select({organiserId:events.organiserId}).from(shows).innerJoin(events,eq(events.id,shows.eventId)).where(eq(shows.id,showId)).limit(1))[0];if(!show||(u.role!=='admin'&&show.organiserId!==u.sub))throw new UnauthorizedException();const rows=await db.select({bookingRef:bookings.bookingRef,status:bookings.status,totalPaise:bookings.totalPaise,createdAt:bookings.createdAt,customerName:users.name,customerEmail:users.email,seatId:bookingSeats.showSeatId,pricePaise:bookingSeats.pricePaise,checkedInAt:bookingSeats.checkedInAt,row:seats.rowLabel,number:seats.seatNumber}).from(bookings).innerJoin(users,eq(users.id,bookings.userId)).innerJoin(bookingSeats,eq(bookingSeats.bookingId,bookings.id)).innerJoin(showSeats,eq(showSeats.id,bookingSeats.showSeatId)).innerJoin(seats,eq(seats.id,showSeats.seatId)).where(eq(bookings.showId,showId)).orderBy(desc(bookings.createdAt));return {bookings:rows}}

 // ── Organiser: revenue summary ───────────────────────────────────────────────
 @Roles('organiser','admin') @Get('organiser/shows/:showId/revenue') async showRevenue(@Param('showId') showId:string,@Req() req:Request){const u=auth(req);const show=(await db.select({organiserId:events.organiserId}).from(shows).innerJoin(events,eq(events.id,shows.eventId)).where(eq(shows.id,showId)).limit(1))[0];if(!show||(u.role!=='admin'&&show.organiserId!==u.sub))throw new UnauthorizedException();const [rev]=await db.select({totalPaise:sql<number>`coalesce(sum(${bookings.totalPaise}),0)`,count:sql<number>`count(*)`}).from(bookings).where(and(eq(bookings.showId,showId),eq(bookings.status,'confirmed')));const [cap]=await db.select({total:sql<number>`count(*)`}).from(showSeats).where(eq(showSeats.showId,showId));const [booked]=await db.select({count:sql<number>`count(*)`}).from(showSeats).where(and(eq(showSeats.showId,showId),eq(showSeats.status,'booked')));return {totalPaise:rev.totalPaise,bookingCount:rev.count,seatCapacity:cap.total,bookedSeats:booked.count}}

 // ── Organiser: waitlist ──────────────────────────────────────────────────────
 @Roles('organiser','admin') @Get('organiser/shows/:showId/waitlist') async showWaitlist(@Param('showId') showId:string,@Req() req:Request){const u=auth(req);const show=(await db.select({organiserId:events.organiserId}).from(shows).innerJoin(events,eq(events.id,shows.eventId)).where(eq(shows.id,showId)).limit(1))[0];if(!show||(u.role!=='admin'&&show.organiserId!==u.sub))throw new UnauthorizedException();const rows=await db.select({id:waitlistEntries.id,status:waitlistEntries.status,category:waitlistEntries.category,offerExpiresAt:waitlistEntries.offerExpiresAt,createdAt:waitlistEntries.createdAt,name:users.name,email:users.email}).from(waitlistEntries).innerJoin(users,eq(users.id,waitlistEntries.userId)).where(eq(waitlistEntries.showId,showId)).orderBy(asc(waitlistEntries.createdAt));return {waitlist:rows}}

 // ── Auth ─────────────────────────────────────────────────────────────────────
 @Public() @Post('auth/register') async register(@Body() body:unknown,@Res({passthrough:true}) res:Response){const input=registerSchema.safeParse(body);if(!input.success)throw new BadRequestException('Invalid registration details');const email=input.data.email.toLowerCase();const existing=await db.select({id:users.id}).from(users).where(eq(users.email,email)).limit(1);if(existing[0])throw new ConflictException('Email already registered');const user=(await db.insert(users).values({name:input.data.name,email,passwordHash:await argon2.hash(input.data.password),role:'customer'}).returning({id:users.id,name:users.name,email:users.email,role:users.role}))[0];return this.issue(user,res)}
 @Public() @Post('auth/login') async login(@Body() body:unknown,@Res({passthrough:true}) res:Response){const input=loginSchema.safeParse(body);if(!input.success)throw new UnauthorizedException('Invalid email or password');const row=(await db.select().from(users).where(eq(users.email,input.data.email.toLowerCase())).limit(1))[0];if(!row||!(await argon2.verify(row.passwordHash,input.data.password)))throw new UnauthorizedException('Invalid email or password');return this.issue({id:row.id,name:row.name,email:row.email,role:row.role},res)}
 @Public() @Post('auth/forgot-password') async forgotPassword(@Body() body:unknown){const input=passwordResetRequestSchema.safeParse(body);if(!input.success)throw new BadRequestException('Invalid email');const user=(await db.select({id:users.id}).from(users).where(eq(users.email,input.data.email.toLowerCase())).limit(1))[0];const response:{ok:boolean;resetToken?:string}={ok:true};if(user){const raw=randomBytes(48).toString('base64url');await db.insert(passwordResetTokens).values({userId:user.id,tokenHash:digest(raw),expiresAt:new Date(Date.now()+30*60_000)});if(process.env.NODE_ENV!=='production')response.resetToken=raw;}return response}
 @Public() @Post('auth/reset-password') async resetPassword(@Body() body:unknown,@Res({passthrough:true}) res:Response){const input=passwordResetSchema.safeParse(body);if(!input.success)throw new BadRequestException('Invalid reset request');const token=(await db.select({id:passwordResetTokens.id,userId:passwordResetTokens.userId}).from(passwordResetTokens).where(and(eq(passwordResetTokens.tokenHash,digest(input.data.token)),gt(passwordResetTokens.expiresAt,new Date()),isNull(passwordResetTokens.usedAt))).limit(1))[0];if(!token)throw new UnauthorizedException('Reset token is invalid or expired');await db.transaction(async tx=>{await tx.update(users).set({passwordHash:await argon2.hash(input.data.password)}).where(eq(users.id,token.userId));await tx.update(passwordResetTokens).set({usedAt:new Date()}).where(eq(passwordResetTokens.id,token.id));await tx.update(refreshTokens).set({revokedAt:new Date()}).where(eq(refreshTokens.userId,token.userId));});res.clearCookie('encore_access',{path:'/'});res.clearCookie('encore_refresh',{path:'/'});return {ok:true}}
 @Post('auth/refresh') async refresh(@Req() req:Request,@Res({passthrough:true}) res:Response){const raw=req.cookies?.encore_refresh;if(!raw)throw new UnauthorizedException();const stored=(await db.select({id:refreshTokens.id,userId:refreshTokens.userId,familyId:refreshTokens.familyId,revokedAt:refreshTokens.revokedAt}).from(refreshTokens).where(and(eq(refreshTokens.tokenHash,digest(raw)),gt(refreshTokens.expiresAt,new Date()))).limit(1))[0];if(!stored)throw new UnauthorizedException();if(stored.revokedAt){await db.update(refreshTokens).set({revokedAt:new Date()}).where(eq(refreshTokens.familyId,stored.familyId));throw new UnauthorizedException('Refresh token reuse detected');}await db.update(refreshTokens).set({revokedAt:new Date()}).where(eq(refreshTokens.id,stored.id));const user=(await db.select({id:users.id,name:users.name,email:users.email,role:users.role}).from(users).where(eq(users.id,stored.userId)).limit(1))[0];return this.issue(user,res,stored.familyId)}
 @Post('auth/logout') async logout(@Req() req:Request,@Res({passthrough:true}) res:Response){const raw=req.cookies?.encore_refresh;if(raw)await db.update(refreshTokens).set({revokedAt:new Date()}).where(eq(refreshTokens.tokenHash,digest(raw)));res.clearCookie('encore_access',{path:'/'});res.clearCookie('encore_refresh',{path:'/'});return {ok:true}}
 @Get('auth/me') me(@Req() req:Request){const u=auth(req);return {session:{id:u.sub,name:u.name,email:u.email,role:roleSchema.parse(u.role)}}}

 // ── Bookings ─────────────────────────────────────────────────────────────────
 @Get('bookings') async myBookings(@Req() req:Request){const u=auth(req);const rows=await db.select({bookingRef:bookings.bookingRef,showId:bookings.showId,status:bookings.status,totalPaise:bookings.totalPaise,createdAt:bookings.createdAt,startsAt:shows.startsAt,eventTitle:events.title,venue:venues.name,city:venues.city}).from(bookings).innerJoin(shows,eq(shows.id,bookings.showId)).innerJoin(events,eq(events.id,shows.eventId)).innerJoin(venues,eq(venues.id,shows.venueId)).where(eq(bookings.userId,u.sub)).orderBy(desc(bookings.createdAt));return {bookings:rows}}
 @Get('bookings/:bookingRef') async booking(@Param('bookingRef') bookingRef:string,@Req() req:Request){const u=auth(req);const row=(await db.select({bookingRef:bookings.bookingRef,showId:bookings.showId,status:bookings.status,totalPaise:bookings.totalPaise,createdAt:bookings.createdAt,startsAt:shows.startsAt,eventTitle:events.title,venue:venues.name,city:venues.city}).from(bookings).innerJoin(shows,eq(shows.id,bookings.showId)).innerJoin(events,eq(events.id,shows.eventId)).innerJoin(venues,eq(venues.id,shows.venueId)).where(and(eq(bookings.bookingRef,bookingRef),eq(bookings.userId,u.sub))).limit(1))[0];if(!row)throw new NotFoundException('Booking not found');const seatRows=await db.select({seatId:bookingSeats.showSeatId,pricePaise:bookingSeats.pricePaise,checkedInAt:bookingSeats.checkedInAt,row:seats.rowLabel,number:seats.seatNumber,section:seats.section,category:seats.category}).from(bookingSeats).innerJoin(showSeats,eq(showSeats.id,bookingSeats.showSeatId)).innerJoin(seats,eq(seats.id,showSeats.seatId)).where(eq(bookingSeats.bookingId,sql`(select id from bookings where booking_ref=${bookingRef})`));return {...row,seats:seatRows}}
 @Post('bookings/:bookingRef/cancel') async cancelBooking(@Param('bookingRef') bookingRef:string,@Req() req:Request){const u=auth(req);const result=await db.transaction(async tx=>{const booking=(await tx.select({id:bookings.id,showId:bookings.showId,status:bookings.status}).from(bookings).where(and(eq(bookings.bookingRef,bookingRef),eq(bookings.userId,u.sub))).for('update').limit(1))[0];if(!booking)throw new UnauthorizedException();if(booking.status==='cancelled')return booking;const seatsToRelease=await tx.select({showSeatId:bookingSeats.showSeatId}).from(bookingSeats).where(eq(bookingSeats.bookingId,booking.id));await tx.update(bookings).set({status:'cancelled'}).where(eq(bookings.id,booking.id));if(seatsToRelease.length)await tx.update(showSeats).set({status:'available',version:sql`${showSeats.version}+1`}).where(and(inArray(showSeats.id,seatsToRelease.map(s=>s.showSeatId)),eq(showSeats.status,'booked')));await tx.insert(jobs).values([{type:'allocate_waitlist',payload:{showId:booking.showId,seatIds:seatsToRelease.map(s=>s.showSeatId)}},{type:'booking_cancellation',payload:{bookingId:booking.id}}]);return {...booking,status:'cancelled'};});this.realtime.emitSeatUpdate(result.showId);return result}

 // ── Confirm booking (with QR token generation) ──────────────────────────────
 @Post('bookings/confirm') async confirm(@Body() body:unknown,@Req() req:Request){const u=auth(req);const input=confirmSchema.safeParse(body);if(!input.success)throw new BadRequestException('Invalid booking request');const result=await db.transaction(async tx=>{const previous=(await tx.select({id:bookings.id,bookingRef:bookings.bookingRef,showId:bookings.showId,qrTokenHash:bookings.qrTokenHash}).from(bookings).where(and(eq(bookings.userId,u.sub),eq(bookings.idempotencyKey,input.data.idempotencyKey))).limit(1))[0];if(previous)return {...previous,isIdempotent:true};const held=await tx.select({id:showSeats.id,showId:showSeats.showId,price:showSeats.heldPricePaise}).from(showSeats).where(and(inArray(showSeats.id,input.data.seatIds),eq(showSeats.heldByUserId,u.sub),eq(showSeats.status,'held'),gt(showSeats.heldUntil,new Date()))).for('update');if(held.length!==input.data.seatIds.length)throw new ConflictException('Your seat hold expired or is no longer yours');if(held.some(seat=>seat.showId!==held[0].showId))throw new ConflictException('All seats must belong to the same show');const total=held.reduce((sum,s)=>sum+(s.price||0),0);const ref=`ENC-${randomUUID().slice(0,8).toUpperCase()}`;const qrRaw=randomBytes(48).toString('base64url');const qrHash=digest(qrRaw);const created=(await tx.insert(bookings).values({userId:u.sub,showId:held[0].showId,totalPaise:total,bookingRef:ref,idempotencyKey:input.data.idempotencyKey,qrTokenHash:qrHash}).returning({id:bookings.id,bookingRef:bookings.bookingRef,showId:bookings.showId}))[0];await tx.insert(bookingSeats).values(held.map(s=>({bookingId:created.id,showSeatId:s.id,pricePaise:s.price||0})));await tx.update(showSeats).set({status:'booked',heldByUserId:null,heldUntil:null,heldPricePaise:null,version:sql`${showSeats.version}+1`}).where(inArray(showSeats.id,input.data.seatIds));if(input.data.holdId)await tx.update(holds).set({status:'converted',convertedAt:new Date()}).where(and(eq(holds.id,input.data.holdId),eq(holds.userId,u.sub)));await tx.insert(jobs).values({type:'booking_confirmation',payload:{bookingId:created.id}});return {...created,qrToken:qrRaw,isIdempotent:false};});this.realtime.emitSeatUpdate(result.showId);return result}

 // ── Shows: seats & hold ──────────────────────────────────────────────────────
 @Public() @Get('shows/:showId/seats') async showSeats(@Param('showId') showId:string){const result=await db.select({id:showSeats.id,row:seats.rowLabel,number:seats.seatNumber,category:seats.category,section:seats.section,pricePaise:sql<number>`coalesce(${showSeats.heldPricePaise},${seats.pricePaise})`,status:sql<string>`case when ${showSeats.status}='held' and ${showSeats.heldUntil}<=now() then 'available' else ${showSeats.status} end`}).from(showSeats).innerJoin(seats,eq(showSeats.seatId,seats.id)).where(eq(showSeats.showId,showId));return {seats:result}}
 @Post('shows/:showId/hold') async hold(@Param('showId') showId:string,@Body() body:unknown,@Req() req:Request){const u=auth(req);const input=holdSchema.safeParse(body);if(!input.success)throw new BadRequestException('Select one to eight seats');const ttl=Number(process.env.SEAT_HOLD_TTL_SECONDS||900);const heldUntil=new Date(Date.now()+ttl*1000);const result=await db.transaction(async tx=>{const held:string[]=[];for(const seatId of input.data.seatIds){const price=(await tx.select({price:seats.pricePaise}).from(seats).where(eq(seats.id,seatId)).limit(1))[0]?.price;if(price===undefined)throw new ConflictException('Seat does not exist');const updated=await tx.update(showSeats).set({status:'held',heldByUserId:u.sub,heldUntil,heldPricePaise:price,version:sql`${showSeats.version}+1`}).where(and(eq(showSeats.id,seatId),eq(showSeats.showId,showId),sql`(${showSeats.status}='available' OR (${showSeats.status}='held' AND ${showSeats.heldUntil}<=now()))`)).returning({id:showSeats.id});if(!updated[0])throw new ConflictException('One or more seats were just taken');held.push(seatId)}const hold=(await tx.insert(holds).values({userId:u.sub,showId,seatIds:held,heldUntil}).returning({id:holds.id}))[0];return {holdId:hold.id,seatIds:held,heldUntil};});this.realtime.emitSeatUpdate(showId);return result}

 // ── Payment simulation ───────────────────────────────────────────────────────
 @Post('shows/:showId/payment-intent') async createPaymentIntent(@Param('showId') showId:string,@Body() body:unknown,@Req() req:Request){const u=auth(req);const {holdId,seatIds,amountPaise}=body as {holdId:string;seatIds:string[];amountPaise:number};if(!holdId||!seatIds?.length||!amountPaise)throw new BadRequestException('holdId, seatIds, amountPaise required');const hold=(await db.select({id:holds.id,userId:holds.userId,status:holds.status,heldUntil:holds.heldUntil}).from(holds).where(and(eq(holds.id,holdId),eq(holds.userId,u.sub),eq(holds.status,'active'),gt(holds.heldUntil,new Date()))).limit(1))[0];if(!hold)throw new ConflictException('Hold is no longer active');const expiresAt=new Date(Date.now()+10*60_000);const payment=(await db.insert(payments).values({userId:u.sub,showId,holdId,seatIds,amountPaise,expiresAt}).returning({id:payments.id,expiresAt:payments.expiresAt}))[0];await db.insert(jobs).values({type:'payment_timeout',payload:{paymentId:payment.id},availableAt:expiresAt});return {paymentId:payment.id,expiresAt:payment.expiresAt}}

 @Post('payments/:paymentId/complete') async completePayment(@Param('paymentId') paymentId:string,@Body() body:unknown,@Req() req:Request){const u=auth(req);const {idempotencyKey}=body as {idempotencyKey:string};if(!idempotencyKey)throw new BadRequestException('idempotencyKey required');const payment=(await db.select().from(payments).where(and(eq(payments.id,paymentId),eq(payments.userId,u.sub),eq(payments.status,'pending'),gt(payments.expiresAt,new Date()))).limit(1))[0];if(!payment)throw new ConflictException('Payment not found or expired');await db.update(payments).set({status:'completed',paidAt:new Date()}).where(eq(payments.id,paymentId));const seatIds=Array.isArray(payment.seatIds)?payment.seatIds as string[]:[];const result=await db.transaction(async tx=>{const previous=(await tx.select({id:bookings.id,bookingRef:bookings.bookingRef,showId:bookings.showId}).from(bookings).where(and(eq(bookings.userId,u.sub),eq(bookings.idempotencyKey,idempotencyKey))).limit(1))[0];if(previous)return {...previous,qrToken:undefined};const held=await tx.select({id:showSeats.id,showId:showSeats.showId,price:showSeats.heldPricePaise}).from(showSeats).where(and(inArray(showSeats.id,seatIds),eq(showSeats.heldByUserId,u.sub),eq(showSeats.status,'held'),gt(showSeats.heldUntil,new Date()))).for('update');if(held.length!==seatIds.length)throw new ConflictException('Seat hold expired');const total=held.reduce((sum,s)=>sum+(s.price||0),0);const ref=`ENC-${randomUUID().slice(0,8).toUpperCase()}`;const qrRaw=randomBytes(48).toString('base64url');const qrHash=digest(qrRaw);const created=(await tx.insert(bookings).values({userId:u.sub,showId:held[0].showId,totalPaise:total,bookingRef:ref,idempotencyKey,qrTokenHash:qrHash}).returning({id:bookings.id,bookingRef:bookings.bookingRef,showId:bookings.showId}))[0];await tx.insert(bookingSeats).values(held.map(s=>({bookingId:created.id,showSeatId:s.id,pricePaise:s.price||0})));await tx.update(showSeats).set({status:'booked',heldByUserId:null,heldUntil:null,heldPricePaise:null,version:sql`${showSeats.version}+1`}).where(inArray(showSeats.id,seatIds));await tx.update(holds).set({status:'converted',convertedAt:new Date()}).where(eq(holds.id,payment.holdId));await tx.insert(jobs).values({type:'booking_confirmation',payload:{bookingId:created.id}});return {...created,qrToken:qrRaw};});this.realtime.emitSeatUpdate(result.showId);return result}

 @Post('payments/:paymentId/cancel') async cancelPayment(@Param('paymentId') paymentId:string,@Req() req:Request){const u=auth(req);const payment=(await db.select().from(payments).where(and(eq(payments.id,paymentId),eq(payments.userId,u.sub),eq(payments.status,'pending'))).limit(1))[0];if(!payment)throw new NotFoundException('Payment not found');await db.update(payments).set({status:'cancelled',cancelledAt:new Date()}).where(eq(payments.id,paymentId));const seatIds=Array.isArray(payment.seatIds)?payment.seatIds as string[]:[];if(seatIds.length){await db.update(showSeats).set({status:'available',heldByUserId:null,heldUntil:null,heldPricePaise:null,version:sql`${showSeats.version}+1`}).where(and(inArray(showSeats.id,seatIds),eq(showSeats.heldByUserId,u.sub)));await db.update(holds).set({status:'cancelled',cancelledAt:new Date()}).where(eq(holds.id,payment.holdId));this.realtime.emitSeatUpdate(payment.showId);}return {ok:true}}

 // ── QR Verify (public) ───────────────────────────────────────────────────────
 @Public() @Get('verify/:token') async verifyQr(@Param('token') token:string){const hash=digest(token);const booking=(await db.select({id:bookings.id,bookingRef:bookings.bookingRef,status:bookings.status,totalPaise:bookings.totalPaise,createdAt:bookings.createdAt,startsAt:shows.startsAt,eventTitle:events.title,venue:venues.name,address:venues.address,city:venues.city,customerName:users.name,customerEmail:users.email}).from(bookings).innerJoin(shows,eq(shows.id,bookings.showId)).innerJoin(events,eq(events.id,shows.eventId)).innerJoin(venues,eq(venues.id,shows.venueId)).innerJoin(users,eq(users.id,bookings.userId)).where(eq(bookings.qrTokenHash,hash)).limit(1))[0];if(!booking)throw new NotFoundException('Invalid or unknown QR token');const seatRows=await db.select({seatId:bookingSeats.showSeatId,pricePaise:bookingSeats.pricePaise,checkedInAt:bookingSeats.checkedInAt,row:seats.rowLabel,number:seats.seatNumber,section:seats.section,category:seats.category}).from(bookingSeats).innerJoin(showSeats,eq(showSeats.id,bookingSeats.showSeatId)).innerJoin(seats,eq(seats.id,showSeats.seatId)).where(eq(bookingSeats.bookingId,booking.id));return {...booking,seats:seatRows}}

 @Roles('organiser','admin') @Post('verify/:token/checkin') async checkinQr(@Param('token') token:string,@Body() body:unknown){const {seatIds}=body as {seatIds:string[]};if(!Array.isArray(seatIds)||!seatIds.length)throw new BadRequestException('seatIds required');const hash=digest(token);const booking=(await db.select({id:bookings.id,status:bookings.status}).from(bookings).where(eq(bookings.qrTokenHash,hash)).limit(1))[0];if(!booking)throw new NotFoundException('Invalid QR token');if(booking.status==='cancelled')throw new ConflictException('Booking is cancelled');const results:{seatId:string;alreadyCheckedIn:boolean}[]=[];for(const seatId of seatIds){const seat=(await db.select({id:bookingSeats.id,checkedInAt:bookingSeats.checkedInAt}).from(bookingSeats).where(and(eq(bookingSeats.bookingId,booking.id),eq(bookingSeats.showSeatId,seatId))).limit(1))[0];if(!seat){results.push({seatId,alreadyCheckedIn:false});continue;}if(seat.checkedInAt){results.push({seatId,alreadyCheckedIn:true});continue;}await db.update(bookingSeats).set({checkedInAt:new Date()}).where(eq(bookingSeats.id,seat.id));results.push({seatId,alreadyCheckedIn:false});}return {results}}

 // ── Waitlist ─────────────────────────────────────────────────────────────────
 @Get('waitlist') async myWaitlist(@Req() req:Request){const u=auth(req);const rows=await db.select({id:waitlistEntries.id,showId:waitlistEntries.showId,status:waitlistEntries.status,category:waitlistEntries.category,offeredSeatIds:waitlistEntries.offeredSeatIds,offerExpiresAt:waitlistEntries.offerExpiresAt,createdAt:waitlistEntries.createdAt,eventTitle:events.title,startsAt:shows.startsAt,venue:venues.name}).from(waitlistEntries).innerJoin(shows,eq(shows.id,waitlistEntries.showId)).innerJoin(events,eq(events.id,shows.eventId)).innerJoin(venues,eq(venues.id,shows.venueId)).where(eq(waitlistEntries.userId,u.sub)).orderBy(desc(waitlistEntries.createdAt));return {waitlist:rows}}
 @Post('waitlist') async waitlist(@Body() body:unknown,@Req() req:Request){const u=auth(req);const input=waitlistSchema.safeParse(body);if(!input.success)throw new BadRequestException('Invalid waitlist request');const existing=(await db.select({id:waitlistEntries.id,status:waitlistEntries.status}).from(waitlistEntries).where(and(eq(waitlistEntries.showId,input.data.showId),eq(waitlistEntries.userId,u.sub),eq(waitlistEntries.status,'waiting'))).limit(1))[0];if(existing)return existing;return (await db.insert(waitlistEntries).values({showId:input.data.showId,category:input.data.category,userId:u.sub}).returning({id:waitlistEntries.id,status:waitlistEntries.status}))[0]}
 @Get('waitlist/:entryId') async waitlistStatus(@Param('entryId') entryId:string,@Req() req:Request){const u=auth(req);const entry=(await db.select({id:waitlistEntries.id,showId:waitlistEntries.showId,status:waitlistEntries.status,category:waitlistEntries.category,offeredSeatIds:waitlistEntries.offeredSeatIds,offerExpiresAt:waitlistEntries.offerExpiresAt,createdAt:waitlistEntries.createdAt,eventTitle:events.title,startsAt:shows.startsAt,venue:venues.name}).from(waitlistEntries).innerJoin(shows,eq(shows.id,waitlistEntries.showId)).innerJoin(events,eq(events.id,shows.eventId)).innerJoin(venues,eq(venues.id,shows.venueId)).where(and(eq(waitlistEntries.id,entryId),eq(waitlistEntries.userId,u.sub))).limit(1))[0];if(!entry)throw new UnauthorizedException();return entry}
 @Post('waitlist/:entryId/claim') async claimWaitlist(@Param('entryId') entryId:string,@Req() req:Request){const u=auth(req);const result=(await db.transaction(async tx=>{const entry=(await tx.select().from(waitlistEntries).where(and(eq(waitlistEntries.id,entryId),eq(waitlistEntries.userId,u.sub),eq(waitlistEntries.status,'offered'),gt(waitlistEntries.offerExpiresAt,new Date()))).for('update').limit(1))[0];if(!entry)throw new ConflictException('This waitlist offer is unavailable or expired');return (await tx.update(waitlistEntries).set({status:'claimed',claimedAt:new Date()}).where(eq(waitlistEntries.id,entryId)).returning({id:waitlistEntries.id,showId:waitlistEntries.showId,status:waitlistEntries.status,seatIds:waitlistEntries.offeredSeatIds}))[0]}));this.realtime.emitSeatUpdate(result.showId);return result}

 // ── Admin ────────────────────────────────────────────────────────────────────
 @Roles('admin') @Get('admin/bookings') async adminBookings(@Query('page') page='1'){const limit=50;const offset=(Number(page)-1)*limit;const rows=await db.select({bookingRef:bookings.bookingRef,status:bookings.status,totalPaise:bookings.totalPaise,createdAt:bookings.createdAt,customerName:users.name,customerEmail:users.email,eventTitle:events.title,venue:venues.name}).from(bookings).innerJoin(users,eq(users.id,bookings.userId)).innerJoin(shows,eq(shows.id,bookings.showId)).innerJoin(events,eq(events.id,shows.eventId)).innerJoin(venues,eq(venues.id,shows.venueId)).orderBy(desc(bookings.createdAt)).limit(limit).offset(offset);return {bookings:rows}}
 @Roles('admin') @Get('admin/users') async adminUsers(){const rows=await db.select({id:users.id,name:users.name,email:users.email,role:users.role,createdAt:users.createdAt}).from(users).orderBy(desc(users.createdAt));return {users:rows}}
 @Roles('admin') @Patch('admin/users/:userId/role') async adminSetRole(@Param('userId') userId:string,@Body() body:unknown){const {role}=body as {role:string};const parsed=roleSchema.safeParse(role);if(!parsed.success)throw new BadRequestException('Invalid role');const updated=(await db.update(users).set({role:parsed.data}).where(eq(users.id,userId)).returning({id:users.id,role:users.role}))[0];if(!updated)throw new NotFoundException('User not found');return updated}
 @Roles('admin') @Get('admin/jobs') async adminJobs(@Query('status') status?:string){const filter=status?eq(jobs.status,status as 'pending'|'processing'|'completed'|'failed'):undefined;const rows=await db.select().from(jobs).where(filter).orderBy(desc(jobs.createdAt)).limit(100);return {jobs:rows}}
 @Roles('admin') @Post('admin/jobs/:jobId/retry') async retryJob(@Param('jobId') jobId:string){const updated=(await db.update(jobs).set({status:'pending',attempts:0,lastError:null,availableAt:new Date()}).where(and(eq(jobs.id,jobId),eq(jobs.status,'failed'))).returning({id:jobs.id}))[0];if(!updated)throw new NotFoundException('Failed job not found');return {ok:true}}

 // ── Private helpers ──────────────────────────────────────────────────────────
 private async issue(u:{id:string;name:string;email:string;role:Role},res:Response,familyId:string=randomUUID()){const refresh=randomBytes(48).toString('base64url');await db.insert(refreshTokens).values({userId:u.id,familyId,tokenHash:digest(refresh),expiresAt:new Date(Date.now()+30*24*60*60*1000)});setCookie(res,'encore_access',accessToken(u),15*60*1000);setCookie(res,'encore_refresh',refresh,30*24*60*60*1000);return {session:{id:u.id,name:u.name,email:u.email,role:u.role}}}
}

@Module({imports:[ThrottlerModule.forRoot([{ttl:60000,limit:100}])],controllers:[RootController,AppController],providers:[RealtimeGateway,{provide:APP_GUARD,useClass:AuthGuard},{provide:APP_GUARD,useClass:ThrottlerGuard}]}) class AppModule{}

async function bootstrap(){
  if(process.env.NODE_ENV==='production'&&(!process.env.DATABASE_URL||!process.env.JWT_ACCESS_SECRET||process.env.JWT_ACCESS_SECRET.length<32))throw new Error('DATABASE_URL and a 32+ character JWT_ACCESS_SECRET are required in production');
  const app=await NestFactory.create(AppModule);
  app.enableCors({origin:process.env.FRONTEND_URL||'http://localhost:3000',credentials:true});
  app.use(require('cookie-parser')());
  await app.listen(Number(process.env.PORT)||4000,'0.0.0.0');
  await db.insert(jobs).values({type:'release_expired_holds',payload:{}});
  startWorker();
}
bootstrap();
